# Training
seed: 42
epochs: 100
batch_size: 64
eta_min: 1.0e-6
learning_rate: 1.0e-4

# Regularization
weight_decay: 0.0
label_smoothing: 0.0
dropout_probability: 0.0
apply_augmentation: False

# Model
img_size: 32
variant: base
patch_size: 16
num_classes: 10
learnable_pe: True
torch_implementation: False