apply_augmentation: true
batch_size: 64
dropout_probability: 0.0
epochs: 100
eta_min: 1.0e-06
img_size: 32
label_smoothing: 0.0
learnable_pe: true
learning_rate: 0.0001
num_classes: 10
patch_size: 16
seed: 42
torch_implementation: true
variant: base
weight_decay: 0.0
